### PR TITLE
Test refactor, making them faster

### LINKED ISSUE #518: Make the E2E tests run faster by launching the browser only once, at the beginning of the testing

### PR DESCRIPTION
**Pull request by ahmadayubi**
time

Refactor and parallelism resulted in tests running in under 2 minutes (or less).
This requires the use of `await page.waitForTimeout(200);` when doing many keyboard interactions in a row to prevent missed keys.

- [x] Certain tests are currently unstable, need fix

Closes #518 (indirect, as instead of launching a single browser, it's launching multiple browsers depending on the device)

### CODE REVIEW

**Comment by prushforth** [comment]
It's fantastic how fast they run.  I ran them 4 times, but had a failure in one run, that disappeared in subsequent runs.  Have you noticed this, and if so is it a setting that could be adjusted?

**Comment by ahmadayubi** [comment]
> It's fantastic how fast they run. I ran them 4 times, but had a failure in one run, that disappeared in subsequent runs. Have you noticed this, and if so is it a setting that could be adjusted?

Do you remember the test? This is probably an issue related to actions being made too quickly. Since mapml-viewer is visual with animations, parts of the code need timeouts to allow the animations and loading to complete.

**Comment by prushforth** [comment]
No I didn't take note. I will play around to see if I encounter it again.

**Comment by Anshpreet8** [comment]
> Do you remember the test? This is probably an issue related to actions being made too quickly. Since mapml-viewer is visual with animations, parts of the code need timeouts to allow the animations and loading to complete.

It appeared I had a failure for mapMLTemplatedFeatures and mapMLTemplatedImageLayer two seperate times, the failures seem to be a result of zooming:
Screen Shot 2021-11-15 at 2 23 04 PM

Screen Shot 2021-11-15 at 2 27 06 PM

**Comment by ahmadayubi** [comment]
> It appeared I had a failure for mapMLTemplatedFeatures and mapMLTemplatedImageLayer two seperate times, the failures seem to be a result of zooming:

Try adding timeouts to parts that seem, for example many keyboard actions at one point, see if that fixes it. Those files for me didn't cause issues but it's very hardware dependent (without timeouts).

**Comment by Anshpreet8** [comment]
> Try adding timeouts to parts that seem, for example many keyboard actions at one point, see if that fixes it. Those files for me didn't cause issues but it's very hardware dependent (without timeouts).

yea, adding a larger timeout number seemed to fix it for me

**Comment by prushforth** [comment]
OK, I couldn't get the tests to fail again on that branch.  It could have to do with caching resources, that happens at levels we might not be aware of.  So, let's merge and deal with issues as they may come.

**Pull request merged**
