### PR TITLE
Add a default projection (OSMTILE) for the map

### PR DESCRIPTION
**Pull request by AliyanH**
- [X] Add default projection of OSMTILE for mapml-viewer
- [X] remove use of 'createmap' event
- [x] resolve issues related with custom projection
- [x] web-map support

**Notes**
**ToDo -** 
- ~~[ ] move createAndAddTemplatedLayers from on add in mapmlLayer to process content similar to how we handler other layer types~~ Should be done as part of map-extent custom element development.
- [X] Add a projection parameter to _convertAndFormatPCRS
- [x] get rid of 'foo' event

**current known issues on experiments (need to re-verify after latest commits) -**

- [x] experiments/painting/ Girl example, clicking on girl does not zoom
- [x] experiments/alternate-style/ maintian opacity across different styles
- [x] experiments/linking/features - clicking on BC does not work, Ontario link not working
- [x] experiments/vector tiles - not working
- [x] legend does not show up as hyperlink for layers with legend (tried a layer with inline content, legend did not appear)

**Other issues/problems found that exist on main also -**
- [x] ZoomTo from layer control on unchecked layer (get layer unchecked by checking and unchecking a few times) throws an error - **resolved in this PR**
- [ ] Need to find a better way of displaying legends, there is already a PR that started some work on this #763, A issue already exists - #524
- [ ] #884
- [ ] #885
- [ ] #882
- [ ] #880
- [ ] #883

**Things to do after this PR is pushed -** 
- Every time a map-feature is updated update the layerbounds dynamically (make GetBounds update dynamically)
- layer.extent needs to be set by the layer- getter which would call the setLayerElExtent
- create separate classes for FeatureLayer.js, for the different use cases such as statictilelayer, query, templated, etc.
- featureRenderer - link between custom element and feature renderer, maybe migrate the resetFeature logic to it later

### CODE REVIEW

**Comment by AliyanH** [comment]
TODO 
-  move createAndAddTemplatedLayers from on add in mapmlLayer to process content similar to how we handler other layer types
- Add a projection parameter to _convertAndFormatPCRS

**Comment by AliyanH** [comment]
current known issues on experiments (need to re-verify after latest commits) -
- experiments/painting/ Girl example, clicking on girl does not zoom
- experiments/alternate-style/ maintian opacity across different styles
- experiments/linking/features - clicking on BC does not work, Ontario link not working
- experiments/vector tiles - not working

Things to do after this PR is pushed - 
- Every time a map-feature is updated update the layerbounds dynamically (make GetBounds update dynamically)
- layer.extent needs to be set by the layer- getter which would call the setLayerElExtent
- featureRenderer - link between custom element and feature renderer, maybe migrate the resetFeature logic to it later

**Comment by prushforth** [comment]
Tests pass on windows, fail on linux (wsl2) locally, same error messages as on CI, so need to figure that out.

**Comment by prushforth** [comment]
The QueryHandler is querying the layer control for the order of map-extent elements, but it should be querying the DOM and / or ShadowDOM for that order, since the layer control may not be in use,only the content of the layer- either in light or shadow root

**Pull request merged**
