### PR TITLE
Tab order based on distance from center

### LINKED ISSUE #385: Assign tabindex=n in ascending order of distance of feature from map centre
It seems that having to tab through every feature in a map viewport could be a burden especially for blind users.  One of the benefits of maps is that sighted users are able to immediately see the relevance of spatial phenomena relative to locations, often the map centre point.  

There should be a way to improve the usability of maps with features for blind users, and I think this might help with one aspect of that, by reducing the amount of tabbing they have to do to get relevant info.  

When a server is involved, it could sort features naturally in that order before serializing the document, without having to set the tab order.  But it should also be a function that can be requested on the client, perhaps with a user preference.  Sorting these things can be an intensive process so it might not be something the viewer should do on every request, but it seems reasonable to allow a user to make it *their* default.

Unsure if there's a UCR issue for this, not at first glance anyway.

### PR DESCRIPTION
**Pull request by ahmadayubi**
https://user-images.githubusercontent.com/55214462/143302447-6f728be5-4dfd-4e09-bbeb-7368421bec97.mp4

- [x] Add tests / adjust tests for new behavior
- [x] Update popup navigation button functionality
- [x] Prevent features off screen from being tab focused

Closes #385

### CODE REVIEW

**Comment by ahmadayubi** [comment]
@prushforth 
Assigning a tab index to features while the map has a `taxindex = 0` means the feature gets focused before the map. Is this the intended/accepted behavior?

**Comment by prushforth** [comment]
> Is this the intended/accepted behavior?

My first impression is that the map should always come first.  It would be acceptable to skip the controls and go straight to the features, maybe.

**Comment by ahmadayubi** [comment]
> > Is this the intended/accepted behavior?
> 
> My first impression is that the map should always come first. It would be acceptable to skip the controls and go straight to the features, maybe.

To get this behavior you either have to;
1. set the `tabindex` of the map to 1
2. remove the `tabindex` values when the map is not focused and re-add `tabindex` only when the map is focused

**Comment by Malvoz** [comment]
I think 2 is the only option, we don't want to break the tab order of elements on people's websites.

**Comment by Malvoz** [comment]
See also:

- https://adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html
- https://dequeuniversity.com/rules/axe/4.0/tabindex
- etc.

**Comment by Malvoz** [comment]
Would this be compatible with https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/571?

**Comment by ahmadayubi** [comment]
> Would this be compatible with #571?

No I believe that's getting shelved for now

**Comment by prushforth** [comment]
Could we establish a private focus order index value that we follow, instead of setting the tabindex > 0?  We could handle keystrokes while in a sequence of features and set focus to the next highest/ next lowest private focus order index, perhaps

**Comment by prushforth** [comment]
I was looking for where @malvoz mentioned using arrow keys instead of tab keys within a group of features.  If we implemented that, we wouldn't be hacking the tabindex, I think.

**Comment by Malvoz** [comment]
> I was looking for where @Malvoz mentioned using arrow keys instead of tab keys within a group of features.

That's https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/535.

**Comment by prushforth** [comment]
So, I think we should be using tabindex=-1 and setting a private focus index value that we programmatically use to set the focus on a feature. The private value can be ordered ascending by distance??   Maybe the first feature in the DOM should be tabindex=0 and the rest -1?  WDYT?

**Comment by ahmadayubi** [comment]
That would work, does handling the tab event ourselves have any benefit over adding tabindex when the map is focused and removing it once the map is out of focus?

**Comment by prushforth** [comment]
Good question, but if we don't change the tabimdex in an antisocial way, it won't matter if our program crashes and can't change it back? Maybe

**Comment by prushforth** [comment]
> Maybe the first feature in the DOM should be tabindex=0 and the rest -1? WDYT?

Maybe the first feature in each layer should be tabindex=0, with the rest =-1...

**Comment by ahmadayubi** [comment]
https://user-images.githubusercontent.com/55214462/143720161-a8aa56af-b3cf-4455-ae87-88be98182af2.mp4

So I opted to use event handlers as this would also further improvements in the future brought up by @prushforth regarding arrow keys.

All the features in the map are considered rather than on a per layer basis. The highest `tabindex` value used is now 0, never exceeding this.

The final thing remaining is treating subparts (spans within coordinates) as independent when sorting, currently it treats subparts distance from the center as equal to the distance of the main component.

**Comment by ahmadayubi** [comment]
The functionality should be reviewed before the tests are updated to reflect the new behavior. So if anyone has time please share any feedback or bugs.

**Comment by prushforth** [comment]
Looking pretty nice!  A couple of things I noticed.

1) for https://maps4html.org/experiments/screenreader/restaurants/ page, if you build your branch and put the dist into a local clone of experiments, it sorts the restaurants very nicely, but if you zoom, you then have to tab twice to get past a marker.

2) in this page with the sorting build in dist https://maps4html.org/experiments/screenreader/closest-restaurants/ if you click the Restaurants button, you'll get the following error:

image

I'll continue to look for stuff....

**Comment by ahmadayubi** [comment]
@prushforth The issues you mentioned should be fixed with the latest update, good finds!

**Comment by prushforth** [comment]
@ahmadayubi the issues seem mostly fixed.  I was able to reproduce the first problem:

> 
> 1. for https://maps4html.org/experiments/screenreader/restaurants/ page, if you build your branch and put the dist into a local clone of experiments, it sorts the restaurants very nicely, but if you zoom, you then have to tab twice to get past a marker.  If you zoom twice, I think you have to tab 3 times to get past a marker, and the number of times you have to tab grows as you change zoom.

but not as bad, by first loading the restaurants, then tabbing through them, then zooming in and tabbing a few times, then right-click the restaurants layer entry and press "Zoom to layer".  The multiple-tabs-to-get-past-a-marker problem occurs.

**Comment by ahmadayubi** [comment]
@prushforth Turns out the reason it needed multiple tab presses is because the features are duplicated in the DOM. The bug is related to `zoomToLayer` in combination with `TemplatedFeaturesLayer`, where the `_pullFeatureFeed` is called twice (through the moveend handler) instead of once, not sure why yet.

**Comment by prushforth** [comment]
I have a feeling that might be due to a change I made during template features processing. So it's an unrelated bug to this.

**Comment by ahmadayubi** [comment]
I've been meaning to fix the zoomToLayer anyways, it has a bad flicker due to how it functions but, I got a fix for it now.

**Review by Malvoz — APPROVED** [review]
LGTM!

This change on its own would make it difficult for screen reader users to discover that new features have become available after pan/zoom, but it's an important piece of the puzzle. And it all comes together with https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/636.

**Review by prushforth — APPROVED** [review]
Looks good to me.  When tabbing through many features, we do need a way to skip  to the end of the sequence so as to not trap the user.  This may come into play with feature indexing too.  I look forward to implementing arrow key feature navigation as a way of leaving tabs to inter-control/interactive element navigation.

**Comment by prushforth** [comment]
Boom!

**Pull request merged**
