### PR TITLE
Add zooming when layer is added using <map-a>

### LINKED ISSUE #378: Zoom to fragment of <map-a href> else zoom to extent of linked resource
A page can have > 1 map on it, but it would be useful to be able to capture the URL fragment and set the map center or bounds based on the parameters found there.  

Maybe it could be in the form of a script that is distributed with the custom elements set, that you could configure easily to "do something" with a page's URL fragment if doing something is possible i.e. the fragment parses as something recognizable as a zoom,lon,lat or bbox etc.

### PR DESCRIPTION
**Pull request by ahmadayubi**
Zooms map to a link url fragment, if that doesn't exist then zoom to the layer extent. 
If `inplace` attribute is present then it doesn't zoom.

Closes #378

### CODE REVIEW

**Comment by prushforth** [comment]
I don't see the zoomTo functionality that I was expecting with non-fragment text/mapml links (actually haven't tested fragments yet)?

For example, this link:`<map-a href="http://localhost:8081/geoserver/mapml/spearfish/cbmtile/">` , which matches the `_self` spec below, is not zooming to the spearfish layer extent when link is activated


_self: (Default if no target attribute) replace the current layer - **not zooming afaict**
_blank: add a new layer on top of map - **not zooming to layer extent afaict**
_parent: replace all layers in the map with the linked layer. If no other layers, behaves as _self. - **not zooming afaict**
_top: the topmost browsing context (the page) should navigate to the map resource, synthesize an HTML document
                around it, and load the map resource into the synthesized map and process any URL fragments to control the
                initial location of the map view. If no fragment, set zoom to lowest value, centered on extent of map doc.
                (the "highest" context that’s an ancestor of the current one). 
                If no ancestors, behaves as _self.  - **not zooming afaict**

**Comment by ahmadayubi** [comment]
That's odd, I got the behavior on my end:
https://user-images.githubusercontent.com/55214462/114193446-87b74100-991c-11eb-84cf-425307b5f440.mp4

Could you try using the featureLink.html file and see if it works there? Run the test server `node test/server.js` and go to http://localhost:30001/featurelinks.html

**Comment by ahmadayubi** [comment]
There was an error with inplace but it should be focusing spearfish when you add it, I'll try using geoserver and see if I can recreate the issue.

**Comment by prushforth** [comment]
There's this error in the console actually, sorry I didn't look before: 
image

**Comment by ahmadayubi** [comment]
Seems to be an issue with timing, the focus() function is called on a layer before the layer's extent is fully processed, although it's strange that the geogratis ones loaded in but geoserver ones didn't.

**Comment by prushforth** [comment]
> Seems to be an issue with timing, the focus() function is called on a layer before the layer's extent is fully processed, although it's strange that the geogratis ones loaded in but geoserver ones didn't.

This was a problem in early iterations. It may have been affected by this PR, perhaps: https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/366

**Comment by ahmadayubi** [comment]
Maybe there should be an event that fires when a layers extent is set, I don't believe there's an event fired from the map that lets you know the layer is fully added, do you know of any?

**Comment by prushforth** [comment]
I used to have the extentloaded event, not sure if that still happens.

**Comment by prushforth** [comment]
I also remember hacking with a labelchanged event.  tbh I have not fully grasped asyn programming techniques, which is probably a major issue in this space.

**Comment by ahmadayubi** [comment]
Probably has to do with the `extentload` event being fired on the first request rather than on when it eventually negotiates the correct projection.

**Comment by prushforth** [comment]
First check of a fragment url such as:

`<map-a href="http://localhost:8081/geoserver/mapml/topp:states/cbmtile/#7,-98,38.5" type="text/mapml" target="_self">`

It seems to zoom to 7, lon=98, lat=38.5, but it doesn't load the states layer.

**Comment by prushforth** [comment]
The latest seems to work better for waiting on projection changes, but still getting the error below for url fragments:

 `<map-a href="http://localhost:8081/geoserver/mapml/topp:states/cbmtile/#6,-96.36158755253881,39.668588667742846">`

image

**Comment by prushforth** [comment]
Seems like this link doesn't work like I was expecting, although it does something (zoom/pan to the specified location):

`<map-a href="#10,-76.474059,45.345151">`

would correspond to the _self, below, I think, with the URL defaulting to the "URL" of the current layer, whether or not it is an actual document is another matter, I guess, since the content could be inline.  We should be able to use fragments like the above with each of the target types below, I think.

_self: (Default if no target attribute) replace the current layer
_blank: add a new layer on top of map
_parent: replace all layers in the map with the linked layer. If no other layers, behaves as _self. 
_top: the topmost browsing context (the page) should navigate to the map resource, synthesize an HTML document
around it, and load the map resource into the synthesized map and process any URL fragments to control the
initial location of the map view. If no fragment, set zoom to lowest value, centered on extent of map doc.
(the "highest" context that’s an ancestor of the current one).
If no ancestors, behaves as _self.

**Comment by ahmadayubi** [comment]
I think in a conversion we had I believe you mentioned that if the type=text/mapml and target=_self it should "simply reposition the viewer with zoomTo()". It was decided that the fragments would only work with type=text/mapml, in which case using the URL of the layer in the case of inline features doesn't work since the URL of the layer is pointing to an html page. In the case of templated features, what value do you get from replacing the layer with itself vs just repositioning?

**Comment by prushforth** [comment]
> It was decided that the fragments would only work with type=text/mapml

Right, but the default is text/mapml, correct? 

>  the URL of the layer is pointing to an html page

That's true, but I don't think it affects the use of that URL as the context for zoom/pan to operations?  I may be missing something though.   I believe the intent was "simply reposition the viewer with zoomTo()". The current behaviour as I mentioned does move the map but not to the coordinates specified.  There's a console error as well:

image

>  In the case of templated features, what value do you get from replacing the layer with itself vs just repositioning?

I would not replace the layer with itself - for urls that begin with #, I would not try to resolve against a base url, I would just invoke zoomTo and hope for the correct result.  In a browser if you put a fragment that doesn't have a corresponding id, the browser doesn't complain, it does nothing, which seems to be the appropriate response in case of error here to.

**Comment by prushforth** [comment]
`<map-a href="#z,lon,lat">` could be considered a declarative API that exposes `zoomTo(zoom, longitude, latitude)`.

**Comment by ahmadayubi** [comment]
So in the case of `<map-a href="#3,12,43">`, the viewer should consider that localhost:3000/mypage.html#3, 12, 34 (for example), try to follow the link according to the target type rules (and assume its text/mapml), and even in the case of a failed loading of the layer the fragment should be honored? Is that correct?

**Comment by ahmadayubi** [comment]
Another note is that the `zoomTo(lat, lon, zoom)`, accepts parameters in the order of `lat, lon, zoom`, and not `zoom, lon, lat`. There's probably a reason why, but that's how it's currently implemented.

**Comment by prushforth** [comment]
> So in the case of <map-a href="#3,12,43">, the viewer should consider that localhost:3000/mypage.html#3, 12, 34 (for example), try to follow the link according to the target type rules (and assume its text/mapml), 

In the case of `href="#..."` I *think* it would be ok to just **assume** the current document, be it an HTML page or a MapML document is the search environment, and if the fragment can be understood (parsed), invoke zoomTo on it, end of story.

> and even in the case of a failed loading of the layer the fragment should be honored? Is that correct?

I would not try to load anything in this case.  Could it be treated as a shortcut?  The idea behind fragment identifiers is that they don't identify anything on a server at all, they are simply processed client side.  So when there is a URL with a fragment, the URL parsing and resolution and loading takes place  and ** then ** the fragment is processed.  So if there is no url, I think it might be safe to assume / perform a zoomTo without otherwise attempting to process the url.

> Another note is that the zoomTo(lat, lon, zoom), accepts parameters in the order of lat, lon, zoom, and not zoom, lon, lat. There's probably a reason why, but that's how it's currently implemented.

OK, that's important to remember and document especially when documenting `<map-a href="...">`

I think I might have had the idea that you might not know the zoom, but you wanted to position the map over a location, but it does look a little funny.

**Comment by ahmadayubi** [comment]
During a discussion it was decided that `<map-a href="#...">` would behave as target="_self" for all target values (_blank, _top, etc.).

If the `href="#..."` then simply `zoomTo()` the location
If the `herf="../#..."` (relative URL with fragment) then resolve the URL, replace the current layer with the resolved URL and finally `zoomTo()` the location

**Comment by prushforth** [comment]
LGTM - great work @ahmadayubi, let's go!

**Comment by prushforth** [comment]
I can't get this URL to load properly, it replaces the whole page:

`<map-a href="https://geogratis.gc.ca/mapml/en/cbmtile/bedrockgeology/#4,-97.4376874,54.2737257" target="_self" type="text/mapml">`

**Pull request merged**
