### PR TITLE
Restructures src directory and implements RollUpJS

### LINKED ISSUE #120: Separate different MapML components to separate files
Separate different layer types, util functions, etc. to separate files to improve readability and organization.

The files can be bundled together during builds using a bundler like [RollupJS](https://rollupjs.org/guide/en/),

### PR DESCRIPTION
**Pull request by ahmadayubi**
Closes #120 

Splits the mapml.js file into several files in the following heirarchy:
src
├── mapml
│   ├── handlers
│   │   ├── ContextMenu.js
│   │   └── QueryHandler.js
│   ├── layers
│   │   ├── ControlLayer.js
│   │   ├── FeatureLayer.js
│   │   ├── ImageLayer.js
│   │   ├── MapLayer.js
│   │   ├── StaticTileLayer.js
│   │   ├── TemplatedFeaturesLayer.js
│   │   ├── TemplatedImageLayer.js
│   │   ├── TemplatedLayer.js
│   │   └── TemplatedTileLayer.js
│   ├── utils
│   │   ├── Constants.js
│   │   └── Util.js
│   └── index.js
├── layer.js
├── map-area.js
├── mapml.css
├── mm-mapp.js
└── web-map.js

To build the entire project including mapml.js inside /dist, run the same grunt task as before (grunt / default).

To generate mapml.js only inside of /dist, run grunt / build.
The PR contains 50+ commits that were necessary according to the following link: 
[Splitting a file while preserving line history](https://devblogs.microsoft.com/oldnewthing/20190916-00/?p=102892)

### CODE REVIEW

**Comment by prushforth** [comment]
Looks pretty good @ahmadayubi ! I noticed a bunch of errors related to playwrite when running npm install.  Are you aware of that?

I'll keep playing with it, will let you know if I see anything else.

**Comment by prushforth** [comment]
Copyright and license notices be embedded in the output *.js files?? Or perhaps in the LICENSE.md or what.  Your thoughts on this.

**Comment by ahmadayubi** [comment]
@prushforth 
>I noticed a bunch of errors related to playwrite when running npm install. Are you aware of that?

These are the messages I get:
message

Are they the same as yours?

**Comment by prushforth** [comment]
> Are they the same as yours?
Sorry I ran something else and lost them.  No they aren't the same. I'll re run and see if it happens again.

**Comment by prushforth** [comment]
The same errors didn't happen again, but I get these, which are pretty close.  It was related to a zip file of a browser...

npm WARN jest-playwright-preset@0.1.3 requires a peer of jest-environment-node@^25.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by prushforth** [comment]
I'm deleting my node_modules and starting over.

**Comment by ahmadayubi** [comment]
> Copyright and license notices be embedded in the output *.js files?? Or perhaps in the LICENSE.md or what. Your thoughts on this.

Maybe having it inside of LICENSE.md might be a good option, not sure.

**Comment by prushforth** [comment]
Here's what I get on a clean install (no node_modules):

"C:\Program Files\nodejs\npm.cmd" "install"

> playwright-core@1.2.1 install C:\Users\prushfor\Documents\GitHub\Web-Map-Custom-Element\node_modules\playwright-core
> node install.js


> playwright@1.2.1 install C:\Users\prushfor\Documents\GitHub\Web-Map-Custom-Element\node_modules\playwright
> node install.js


(node:6984) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, unlink 'C:\Users\prushfor\AppData\Local\Temp\playwright-download-webkit-win64-1301.zip'
(node:6984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


more non-critical stuff here.

**Comment by prushforth** [comment]
I'll get rid of that file and run it again.

**Comment by prushforth** [comment]
All clear, must be an issue with re-installing playwright.

**Pull request merged**
