### PR TITLE
prevent the default scrolling event of spacebar when focus is on map

### LINKED ISSUE #694: Page jumps when keyboard query activated
https://geogratis.gc.ca/mapml/en/cbmtile/fdi/

When the \<mapml-viewer> is a block element in a scrollable page, and the query reticle is displayed (because the map has focus), hitting spacebar (activating the query) causes the page to quickly and annoyingly scroll down then up.  Hitting Enter also activates the query, but not the annoying scroll jump.

This doesn't happen when the map is the whole page, for example when fullscreen is active.

### PR DESCRIPTION
**Pull request by yhy0217**
Closes #694
-  [x]  Update web-map.js
-  [x]  Add test for web-map.js

### CODE REVIEW

**Comment by AliyanH** [comment]
f81681f also resolves #719

**Comment by prushforth** [comment]
I am getting a local failure of mapml-viewer.test.js in "Paste Invalid link to map using ctrl+v".

**Review by prushforth — APPROVED** [review]
I listened to the experiments with this PR running, and the maps sound good.  Let's merge it!

Good job!

**Review by AliyanH — APPROVED** [review]
LGTM! Good work

**Pull request merged**
