### PR TITLE
Ahmad demo

### PR DESCRIPTION
**Pull request by prushforth**

### CODE REVIEW

**Comment by ahmadayubi** [comment]
Those demo file are being separated based on the presentation?

**Comment by prushforth** [comment]
More or less, yeah

**Comment by prushforth** [comment]
@ahmadayubi Do you have any concerns about this PR?  I can close it without merging if so...

**Comment by ahmadayubi** [comment]
No I don't have any concerns, the separation doesn't entirely make sense to me but if you felt it's needed then I don't see any issues.

**Pull request closed without merging**
