### PR TITLE
Fix bug that causes unintentional activation when dropping layer items

### PR DESCRIPTION
**Pull request by Malvoz**
Fix: #254.

This also (somehow, unintentionally 🤭) fixes a related bug where it wasn't possible to drag the last item in the layers list.

## Preview

https://user-images.githubusercontent.com/26493779/105442782-ad607280-5c6a-11eb-9d84-70c51dbe0918.mp4

### CODE REVIEW

**Comment by ahmadayubi** [comment]
What was the bug previously? I can't seem to reproduce it on the current geogratis build, just want to make sure it's not a bug anymore.

**Comment by Malvoz** [comment]
@ahmadayubi the bug can be seen in the corresponding issue: https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/254. If you've pulled in the latest commits, you should be able to reproduce in any test/demo page that has multiple layers, e.g. test/e2e/core/debugMode.html.

> I can't seem to reproduce it on the current geogratis build

I think Peter has to manually update the script on geogratis to pull in the latest changes, I don't think we should be testing against geogratis (see https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/162#issuecomment-729174396).

**Comment by ahmadayubi** [comment]
https://user-images.githubusercontent.com/55214462/105737946-8329e180-5f04-11eb-86b0-626d96fa949f.mp4

It seemed to work for me, I also had no issue dragging the last layer in the list either.

**Comment by Malvoz** [comment]
I double checked 20 minutes ago, I can still reproduce on Chrome 88.0.4324.104, Windows 10.0.19042 build 19042.

**Comment by ahmadayubi** [comment]
That's odd, @prushforth are you able to reproduce the bug also? It could be someone on my end?

**Comment by Malvoz** [comment]
I can also reproduce the issue in Firefox (84.0.2).

**Review by ahmadayubi — APPROVED** [review]
I can't reproduce the issue in chrome but if this solved the issue for others then there's no harm in merging it, it won't break anything existing.

**Comment by prushforth** [comment]
I can confirm the issue in firefox 82, but I can't reproduce it in chrome, using the HEAD of this repo's index.html.  I also confirm inability to re-order the last item in the list. I'll merge this and we'll work from there.

**Pull request merged**
