### PR TITLE
Add role='application' to FeatureGroup <g> element

### LINKED ISSUE #423: Popups are misplaced when using a screen reader
I'm getting a strange bug where the popup is misplaced when opening it by pressing <kbd>Enter</kbd>,  _only_ when using a screen reader (NVDA in this case):

<table><td width="400"><video src="https://user-images.githubusercontent.com/26493779/106805628-3c0bc100-6667-11eb-947e-585c9f68525a.mp4"></video></td></table>

_Originally posted by @Malvoz in https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/270#issuecomment-772808780_

### PR DESCRIPTION
**Pull request by prushforth**
Fixes #423

### CODE REVIEW

**Comment by Malvoz** [comment]
It seems that NVDA announces everything on the page after pressing a feature to open a popup. At this point, I'm starting to think we're doing the user a disservice by not just making the entire map `role="application"`.

**Comment by prushforth** [comment]
Ok I'll have a look at that when I get a chance.

**Comment by Malvoz** [comment]
Maybe we should just go ahead and replace `role="region"` of the maps (in web-map.js as well) with `role="application"` (and close out https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/274).

I'll go ahead and do some testing with that approach, see how it behaves.

**Comment by prushforth** [comment]
For some reason I didn't experience NVDA  reading the whole page. I only tried it on the restaurant page though.

**Pull request closed without merging**
