### PR TITLE
Minify and concatenate CSS

### PR DESCRIPTION
**Pull request by Malvoz**
Small performance improvement. Fixes:

> - [ ] Minify and concatenate CSS files

of https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/153.

### CODE REVIEW

**Comment by Malvoz** [comment]
(tests are consistently failing on my machine even on the main branch so I'm just winging it, hoping all goes well 🤞🏼)

**Comment by ahmadayubi** [comment]
> (tests are consistently failing on my machine even on the main branch

If all the tests are failing you may need to run npm install, one of the packages related to testing was updated.

**Comment by Malvoz** [comment]
@ahmadayubi npm install doesn't seem to have an effect on either branch (other than changing package-lock.json on the main branch, which was updated in this PR), the tests still fail most of the time, I'd say about 90% of the time. I tried increasing waitForTimeout in the failing keyboardinteraction and featurelinks tests and saw some improvements but still haven't figured it out.

**Comment by prushforth** [comment]
I still get errors sometimes on main, fwiw.  I will try to fix those; that might improve the chances of this working.

**Comment by prushforth** [comment]
I **hope** that if you pull from upstream main now that the tests will run. I commented out one suite that was causing problems.

**Comment by prushforth** [comment]
So that didn't work.  I'll have to try again locally, although the problem this time appeared in trying to select stuff but timing out, which may indicate some possibly CSS related commit  issue.

**Comment by Malvoz** [comment]
We can close this out, and try again after tests are more stable?

**Comment by prushforth** [comment]
@Malvoz when I reversed the order of combining the css files, I get a pile of error messages that look like what's happening on the gh  action job.  Don't know if that means anything.

**Comment by Malvoz** [comment]
The order of the combined CSS files is important, if it was reversed then leaflet.css would overwrite mapml.css styles. Anyhow, I saw pretty much the same issues on the main branch as I did with this, and even this branch passed the test runs on a few occasions locally so I don't think it's got to do with concatenating the files.

Again I think it's best to revisit this later. Thanks for looking into it though. 😋

**Comment by Malvoz** [comment]
The test runs passed twice locally, thought I was good to go. 😝

**Pull request closed without merging**
